server:
  port: 8081

spring:
  application:
    name: mall-service
  datasource:
    url: jdbc:mysql://localhost:3306/campus_mall?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 18502249082WWW
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

campus:
  jwt:
    secret: campus-mall-secret-key-2026-campus-mall-secret
    expire-hours: 2
